#.//button[text()='Войти в аккаунт'] - кнопка "Войти в аккаунт"
#//div[label[text()='Email']]//input[@type='text'] - поле "Email"
#//div[label[text()='Пароль']]//input[@type='password'] - поле "Пароль"
#.//button[text()='Войти' - кнопка "Войти"
#.//button[text()='Оформить заказ'] - кнопка "Оформить заказ"
#//a[@href='/account'] - кнопка "Личный кабинет"
#//a[@href='/account/profile'] - кнопка "Профиль"
#//button[text()='Выход'] - кнопка "Выход"
#//a[@href='/register'] - ссылка "Зарегистрироваться"
#//a[@href='/login'] - ссылка "Войти"
#//a[@href='/forgot-password'] - ссылка "Восстановить пароль"
#//a[.//p[normalize-space()='Конструктор']] - кнопка "Конструктор"
#/html/body/div/div/main/section[1]/h1 - заголовок "Собери бургер"
#//*[@id='root']/div/header/nav/div - логотип "Stellar Burgers"
#//span[text()='Соусы'] - кнопка "Соусы"
#//div[contains(@class, 'tab_tab_type_current') and .//span[normalize-space()='Соусы']] - выделенная кнопка "Соусы"
#//span[text()='Булки'] - кнопка "Булки"
#//div[contains(@class, 'tab_tab_type_current') and .//span[normalize-space()='Булки']] - выделенная кнопка "Булки"
#//section//h2[normalize-space()='Соусы'] - заголовок раздела "Соусы"
#//section//h2[normalize-space()='Булки'] - заголовок раздела "Булки"
#//span[text()='Начинки'] - кнопка "Начинки"
#//div[contains(@class, 'tab_tab_type_current') and .//span[normalize-space()='Начинки']] - активная кнопка "Начинки"
#//section//h2[normalize-space()='Начинки'] - заголовок раздела "Начинки"
#.//button[text()='Зарегистрироваться'] - кнопка "Зарегистрироваться"
#.//main/div/h2[text()='Вход'] - заголовок "Вход"
#.//fieldset/div/p - ошибка валидации пароля