login_account_button = ".//button[text()='Войти в аккаунт']" #кнопка "Войти в аккаунт"
email_field = "//div[label[text()='Email']]//input[@type='text']" #поле "Email"
password_field = "//div[label[text()='Пароль']]//input[@type='password']" #поле "Пароль"
login_button = ".//button[text()='Войти']" #кнопка "Войти"
order_button = ".//button[text()='Оформить заказ']" #кнопка "Оформить заказ"
personal_account_button = "//a[@href='/account']" #кнопка "Личный кабинет"
profile_button = "//a[@href='/account/profile']" #кнопка "Профиль"
logout_button = "//button[text()='Выход']" #кнопка "Выход"
registration_link = "//a[@href='/register']" #ссылка "Зарегистрироваться"
login_link = "//a[@href='/login']" #ссылка "Войти"
password_recover_button = "//a[@href='/forgot-password']" #ссылка "Восстановить пароль"
constructor_button = "//a[.//p[normalize-space()='Конструктор']]" #кнопка "Конструктор"
create_burger_header = "/html/body/div/div/main/section[1]/h1" #заголовок "Собери бургер"
stellar_burgers_logo = "//*[@id='root']/div/header/nav/div" #логотип "Stellar Burgers"
sauses_button = "//span[text()='Соусы']" #кнопка "Соусы"
selected_sauses_button = "//div[contains(@class, 'tab_tab_type_current') and .//span[normalize-space()='Соусы']]" #выделенная кнопка "Соусы"
bread_button = "//span[text()='Булки']" #кнопка "Булки"
selected_bread_button = "//div[contains(@class, 'tab_tab_type_current') and .//span[normalize-space()='Булки']]" #выделенная кнопка "Булки"
sauses_header = "//section//h2[normalize-space()='Соусы']"#заголовок раздела "Соусы"
bread_header = "//section//h2[normalize-space()='Булки']" #заголовок раздела "Булки"
fillings_button = "//span[text()='Начинки']" #кнопка "Начинки"
selected_fillings_button = "//div[contains(@class, 'tab_tab_type_current') and .//span[normalize-space()='Начинки']]" #активная кнопка "Начинки"
fillings_header = "//section//h2[normalize-space()='Начинки']" #заголовок раздела "Начинки"
registration_button = ".//button[text()='Зарегистрироваться']" #кнопка "Зарегистрироваться"
login_header = ".//main/div/h2[text()='Вход']" #заголовок "Вход"
validation_error = ".//fieldset/div/p" #ошибка валидации пароля
name_field = "//div[label[text()='Имя']]//input[@type='text']" #поле "Имя"
